### ISSUE TITLE
AR marker support

### ISSUE THREAD

**Issue by Veix123** [robotont/robotont_gazebo#15]
We should have some world files with AR marker(s), so that AR tracking demos can be run also in Gazebo. Investigate simple animation options for the marker.

**Comment by kruusamae** [comment]
@mmaao 
1. create another issue to describe the AR tag animation lag problem
2. create a world where different AR tags are fixed and visible to complete a path using AR tags

**Comment by kruusamae** [comment]
@mmaao see my previous comment

**Comment by kruusamae** [comment]
#37
