### ISSUE TITLE
[ign] unable to get odometry

### ISSUE THREAD

**Issue by kruusamae** [robotont/robotont_gazebo#27]

**Comment by FabianPG11** [comment]
Currently the only pluging on ignition gazebo able to provide odometry is diff_drive. 

[https://github.com/ignitionrobotics/ign-gazebo/issues/465]
Due robotont is an omnidirectional robot, it might not be the right plugin to use; however, as a test in the melodic-devel-ign-gazebo-odom-plugin branch I include this plugin (dif_drive) in the robotont model, and it has a good approximation so far.

**Comment by kruusamae** [comment]
540b72fd386d460040b5e1d254488a306b861471
