### ISSUE TITLE
[ign] add support for minimaze world

### ISSUE THREAD

**Issue by kruusamae** [robotont/robotont_gazebo#29]

**Comment by FabianPG11** [comment]
For some reason I couldn't import the same meshes and materials used for the simulation on robotont- gazebo classic. 
For now, I created a solid part with the entire maze as .stl and imported it into the world.

**Comment by FabianPG11** [comment]
I could include the meshes used on the classic gazebo, so there are two versions of the minimaze (with those meshes and a single solid part). 
Current problem: the texture is not displayed.

**Comment by kruusamae** [comment]
540b72fd386d460040b5e1d254488a306b861471
