### ISSUE TITLE
Clarify why angular motion in gazebo was incorrect.

### ISSUE THREAD

**Issue by Veix123** [robotont/robotont_gazebo#6]
Investigating the need for the driver hack causes some confusion...
In 59299d9ae77c64bbf56b5d1b4e4e9b7eb6a8073a we saw really slow rotational speeds.
In the next commit 82e107cf9712b896e43905ef498c786b4e6d5629 many changes were introduced in xacro files as well as adding params/node for the driver hack.
Interestingly, driver_hack:=false gazebo is not subscribing to the topics published in the gazebo_driver node but still to the cmd_vel.
Nevertheless, something has fixed the problem between these commits! No matter if the driver_hack is true or false, the model now responds to cmd_vel as expected. So what happened in these two commits that made stuff work?

**Comment by kruusamae** [comment]
@FabianPG11 please take a look at this. let's try to get to the bottom of it :)

**Comment by mmaao** [comment]
No idea why, but including the realsense camera does the trick.. the robot won't turn when it's missing.

**Comment by kruusamae** [comment]
that is soooooo counterintuitive. i could understand if adding some third-party components to our robot would slow it down, not the other way around.
